# see https://symfony.com/doc/current/reference/configuration/framework.html
parameters:
    default_trusted_hosts: '^.*$'

framework:
    secret: '%env(APP_SECRET)%'
    csrf_protection: true

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        name: packagist
        cookie_lifetime: 3600
        cookie_httponly: true
        cookie_secure: auto
        cookie_samesite: lax
        handler_id: Symfony\Component\HttpFoundation\Session\Storage\Handler\RedisSessionHandler

    #esi: true
    fragments: true
    form: true
    assets:
        version: 'v=%env(default::ASSETS_VERSION)%'

    http_client:
        default_options:
            headers:
                'User-Agent': 'packagist.org'
            max_redirects: 5
            retry_failed:
                max_retries: 3
            max_duration: 30 # default total duration timeout in seconds, override it per use case with more appropriate values
            timeout: 3

    trusted_hosts: ['%env(string:default:default_trusted_hosts:TRUSTED_HOSTS)%']
    # remote_addr is set to the correct client IP but we need to mark it trusted so that Symfony picks up the X-Forwarded-Host,
    # X-Forwarded-Port and X-Forwarded-Proto headers correctly and sees the right request URL
    trusted_proxies: '127.0.0.1,REMOTE_ADDR'
    # Use all X-Forwarded-* headers from ELB except X-Forwarded-For as nginx handles the IP resolution
    trusted_headers: ['x-forwarded-proto', 'x-forwarded-port']

    property_info:
        with_constructor_extractor: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
