monolog:
    channels:
        - deprecation # Deprecations are logged in the dedicated "deprecation" channel when it exists

when@dev:
    monolog:
        handlers:
            main:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug
                channels: ["!event"]
            console:
                type:   console
                process_psr_3_messages: false
                bubble: false
                verbosity_levels:
                    VERBOSITY_VERBOSE: INFO
                    VERBOSITY_VERY_VERBOSE: DEBUG
                channels: ["!event", "!doctrine", "!console"]
            console_debug:
                type:   console
                process_psr_3_messages: false
                bubble: false
                verbosity_levels:
                    VERBOSITY_VERBOSE: NOTICE
                    VERBOSITY_VERY_VERBOSE: NOTICE
                    VERBOSITY_DEBUG: DEBUG
                channels: ["doctrine", "event", "console"]

when@prod:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [400, 404, 405]
                buffer_size: 100 # How many messages should be saved? Prevent memory leaks
            nested:
                type: stream
                formatter: 'monolog.formatter.json'
                path: "%kernel.logs_dir%/packagist.log"
                level: debug
                include_stacktraces: true

            deprecation:
                type: stream
                formatter: 'monolog.formatter.json'
                path: "%kernel.logs_dir%/deprecations.log"
                include_stacktraces: true
                channels: [deprecation]

#            console:
#                type: console
#                process_psr_3_messages: false
#                channels: ["!event", "!doctrine"]
            console_debug:
                type:   console
                process_psr_3_messages: false
                include_stacktraces: true
                verbosity_levels:
                    VERBOSITY_NORMAL: EMERGENCY
                    VERBOSITY_VERBOSE: INFO
                    VERBOSITY_VERY_VERBOSE: NOTICE
                    VERBOSITY_DEBUG: DEBUG

when@test:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                channels: ["!event"]
            nested:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug
