snc_redis:
    clients:
# Define your clients here. The example below connects to database 0 of the default Redis server.
#
# See https://github.com/snc/SncRedisBundle/blob/master/docs/README.md for instructions on
# how to configure the bundle.
#
#        default:
#            type: phpredis
#            alias: default
#            dsn: "%env(REDIS_URL)%"
        default:
            type: predis
            alias: default
            dsn: '%env(REDIS_URL)%'
            options:
                connection_timeout: 1
                commands:
                    fetchVersionIds: 'App\Redis\FetchVersionIds'
                    downloadsIncr: 'App\Redis\DownloadsIncr'
                    packagesExist: 'App\Redis\PackagesExist'

        cache:
            type: predis
            alias: cache
            dsn: '%env(REDIS_CACHE_URL)%'
            options:
                connection_timeout: 1
                commands:
                    incrFailedLoginCounter: 'App\Redis\FailedLoginCounter'
