fos_user_profile:
    resource: '@FOSUserBundle/Resources/config/routing/profile.xml'
    prefix: /profile

fos_user_profile_show:
    path: /profile/
    defaults: { _controller: App\Controller\UserController::viewProfileAction }
    methods: [GET]

fos_user_register:
    resource: '@FOSUserBundle/Resources/config/routing/registration.xml'
    prefix: /register

fos_user_resetting:
    resource: '@FOSUserBundle/Resources/config/routing/resetting.xml'
    prefix: /resetting

fos_user_change_password:
    resource: '@FOSUserBundle/Resources/config/routing/change_password.xml'


hwi_oauth_connect:
    resource: '@HWIOAuthBundle/Resources/config/routing/connect_41.xml'
    prefix:   /connect

# overrides the fosub /login page
hwi_oauth_login:
    resource: '@HWIOAuthBundle/Resources/config/routing/login_41.xml'
    prefix:   /login

hwi_oauth_redirect:
    resource: '@HWIOAuthBundle/Resources/config/routing/redirect_41.xml'
    prefix:   /login

github_check:
    path: /login/check-github

logout:
    path: /logout
