services:
    packagist.twig.extension:
        class: Packagist\WebBundle\Twig\PackagistExtension
        arguments: [ @doctrine ]
        tags:
            - { name: twig.extension }

    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
            - { name: twig.extension }

    packagist.package_dumper:
        class: Packagist\WebBundle\Package\Dumper
        arguments: [ @doctrine, @filesystem, @router, %kernel.root_dir%/../web/, %kernel.cache_dir% ]

    packagist.user_provider:
        class: Packagist\WebBundle\Security\Provider\UserProvider
        public: false
        arguments: ["@fos_user.user_manager"]

    packagist.user_repository:
        class: Packagist\WebBundle\Entity\UserRepository
        factory_service: doctrine
        factory_method: getRepository
        arguments: ["PackagistWebBundle:User"]

    packagist.package_repository:
        class: Packagist\WebBundle\Entity\PackageRepository
        factory_service: doctrine
        factory_method: getRepository
        arguments: ["PackagistWebBundle:Package"]

    packagist.package_updater:
        class: Packagist\WebBundle\Package\Updater
        arguments: [@doctrine]

    packagist.form.handler.registration:
        class: Packagist\WebBundle\Form\Handler\RegistrationFormHandler
        parent: fos_user.registration.form.handler.default
        scope: request

    fos_user.util.user_manipulator:
        class: Packagist\WebBundle\Util\UserManipulator
        arguments: [@fos_user.user_manager, @fos_user.util.token_generator]

    packagist.oauth.registration_form_handler:
        class: Packagist\WebBundle\Form\Handler\OAuthRegistrationFormHandler
        arguments: [@fos_user.user_manager, @fos_user.util.token_generator]

    packagist.oauth.registration_form_type:
        class: Packagist\WebBundle\Form\Type\OAuthRegistrationFormType
        tags:
            - { name: form.type, alias: packagist_oauth_user_registration }

    packagist.oauth.registration_form:
        factory_method: create
        factory_service: form.factory
        class: Symfony\Component\Form\Form
        arguments:
            - 'packagist_oauth_user_registration'

    packagist.favorite_manager:
        class: Packagist\WebBundle\Model\FavoriteManager
        arguments:
            - @snc_redis.default_client
            - @packagist.package_repository
            - @packagist.user_repository

    packagist.package_manager:
        class: Packagist\WebBundle\Model\PackageManager
        arguments:
            - @doctrine.orm.entity_manager
            - @mailer
            - @twig
            - @logger
            - { from: %mailer_from_email%, fromName: %mailer_from_name% }

    packagist.profile.form.type:
        class: Packagist\WebBundle\Form\Type\ProfileFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: packagist_user_profile }
