imports:
    - { resource: config.yml }

framework:
    router:   { resource: '%kernel.root_dir%/config/routing_dev.yml' }
    profiler: { only_exceptions: false }

swiftmailer:
    disable_delivery: true

web_profiler:
    toolbar: true
    intercept_redirects: false

monolog:
    handlers:
        main:
            type:  stream
            path:  %kernel.logs_dir%/%kernel.environment%.log
            level: debug
            channels: ['!event']
        firephp:
            type:  firephp
            level: info

hwi_oauth:
    http_client:
        verify_peer: false

#assetic:
#    use_controller: true
