imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: %kernel.debug%
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    translator:      { fallback: en }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    default_locale: %locale%
    session:
        name: packagist
        cookie_lifetime: 3600
    trusted_proxies: %trusted_proxies%
    trusted_hosts: %trusted_hosts%
    http_method_override: true
    fragments: ~

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    globals:
        google_analytics: %google_analytics%
        packagist_host: %packagist_host%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    filters:
        cssrewrite: ~
        closure:
            jar: %kernel.root_dir%/java/compiler.jar
        yui_css:
            jar: %kernel.root_dir%/java/yuicompressor-2.4.2.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

snc_redis:
    clients:
        default:
            type: predis
            alias: default
            dsn: %redis_dsn%

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }

fos_user:
    db_driver:     orm
    firewall_name: main
    user_class:  Packagist\WebBundle\Entity\User
    use_username_form_type: true
    from_email:
        address:        %mailer_from_email%
        sender_name:    %mailer_from_name%
    registration:
        form:
            handler: packagist.form.handler.registration
    profile:
        form:
            type:       packagist_user_profile

hwi_oauth:
    firewall_name: main
    connect:
        account_connector: packagist.user_provider
        registration_form_handler: packagist.oauth.registration_form_handler
        registration_form: packagist.oauth.registration_form
    resource_owners:
        github:
            type:          github
            client_id:     %github.client_id%
            client_secret: %github.client_secret%

nelmio_solarium: ~
