name: "Continuous Integration"

on:
  - push
  - pull_request

env:
  APP_ENV: test
  DATABASE_URL: "mysql://root:root@127.0.0.1:3306/packagist?serverVersion=8.0"

jobs:
  tests:
    name: "CI"

    runs-on: ubuntu-24.04-arm

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - uses: shivammathur/setup-php@bf6b4fbd49ca58e4608c9c89fba0b8d90bd2a39f # 2.35.5
        with:
          coverage: "none"
          extensions: "intl, zip, apcu"
          php-version: "8.4"
          tools: composer
          ini-values: apc.enable_cli=1

      - name: "Start MySQL"
        run: sudo systemctl start mysql.service

      - uses: ramsey/composer-install@3cf229dc2919194e9e36783941438d17239e8520 # 3.1.1
        with:
            composer-options: "--ansi --no-interaction --no-progress --prefer-dist"

      - name: Start Redis
        uses: supercharge/redis-github-action@bc274cb7238cd63a45029db04ee48c07a72609fd # 1.8.1
        with:
          redis-version: 6

      - name: "Setup DB"
        run: |
          bin/console doctrine:database:create -n
          bin/console doctrine:schema:create -n

      - name: "Run tests"
        run: "composer test"
