name: "PHP Lint"

on:
  - push
  - pull_request

jobs:
  tests:
    name: "Lint"

    runs-on: ubuntu-24.04-arm

    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1

      - uses: shivammathur/setup-php@44454db4f0199b8b9685a5d763dc37cbf79108e1 # 2.36.0
        with:
          coverage: "none"
          extensions: "intl"
          php-version: "8.4"

      - name: "Lint PHP files"
        run: "find src/ -type f -name '*.php' -print0 | xargs -0 -L1 -P4 -- php -l -f"
