name: "PHPStan"

on:
  - push
  - pull_request

env:
  APP_ENV: dev
  DATABASE_URL: "mysql://root:root@127.0.0.1:3306/packagist?serverVersion=8.0"

jobs:
  tests:
    name: "PHPStan"

    runs-on: ubuntu-24.04-arm

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - uses: shivammathur/setup-php@cf4cade2721270509d5b1c766ab3549210a39a2a # 2.33.0
        with:
          coverage: "none"
          extensions: "intl, zip, apcu"
          php-version: "8.4"
          tools: composer
          ini-values: apc.enable_cli=1

      - name: "Start MySQL"
        run: sudo systemctl start mysql.service

      - uses: ramsey/composer-install@a2636af0004d1c0499ffca16ac0b4cc94df70565 # 3.1.0
        with:
          composer-options: "--ansi --no-interaction --no-progress --prefer-dist"

      - name: "Setup DB"
        run: |
          bin/console doctrine:database:create -n
          bin/console doctrine:schema:create -n

      - name: Run PHPStan
        run: composer phpstan
