name: "PHPStan"

on:
  - push
  - pull_request

env:
  APP_ENV: dev
  DATABASE_URL: "mysql://root:root@127.0.0.1:3306/packagist?serverVersion=8.0"

jobs:
  tests:
    name: "PHPStan"

    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v3"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          extensions: "intl, zip, apcu"
          php-version: "8.3"
          tools: composer
          ini-values: apc.enable_cli=1

      - name: "Start MySQL"
        run: sudo systemctl start mysql.service

      - name: "Install dependencies"
        uses: "ramsey/composer-install@v2"
        with:
          composer-options: "--ansi --no-interaction --no-progress --prefer-dist"

      - name: "Setup DB"
        run: |
          bin/console doctrine:database:create -n
          bin/console doctrine:schema:create -n

      - name: Run PHPStan
        run: composer phpstan
